#include<iostream>
using namespace std;

float divide(float num, float denom) {
   if ( denom == 0 ) {
      throw "EXCEPTION Not possible";
   }
   else {
      return (num / denom);
   }
}

int main() {
	int x,y;
  cin>>x>>y;
   /* protect the piece of code using try ... catch block
      and prevent crashing of the program */
   try {
      float result = divide(x, y);
      cout <<"VALID" << endl;
   } catch (const char *err_msg) {
      cout << err_msg << endl;
   }
   return 0;
}
