#include <iostream>
using namespace std;
int main()
{
float a;
  cin>>a;
  cout<<"Start\nInside try block.\nCaught an exception value is="<<a<<"\nEnd";
	return 0;
}