#include<iostream>
#include<cmath>
#include<string>

using namespace std;
int main(void)
{
string s;
  char a;
getline (cin,s);
  cout << "Start" << endl;
try {

cout << "Inside try block." << endl;

throw a;
cout << "This will not execute.";
}
catch(char i) {
cout << "Caught an exception value is="<<s;
cout << i << endl;
}
cout << "End";
return 0;
}